---
abstract: 'Openstreetmap XML dump parser'
author:
  - 'liosha <liosha@cpan.org>'
build_requires:
  English: 0
  List::MoreUtils: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Openstreetmap-Parser
requires:
  XML::Parser: 0
  autodie: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 0.02
